import React from "react"
import Head from "next/head"
import Footer from "./Footer"
import Navbar from "./Navbar"

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + "- Blockchain" : "Blockchain"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <Navbar/>
        <main>{children}</main>
        <Footer/>
      </div>
    </>
  )
}
